start:
	export FLASK_ENV=development && python app/app.py
	
prod:
	export FLASK_ENV=production && python run.py

venv:
	virtualenv ENV
	# source ./bin/activate

install:
	pip install -r requirements.txt